project:
  type: website
  output-dir: docs

website:
  title: "Sydney Informatics Hub Course name"
  site-url: https://sydney-informatics-hub.github.io/
  navbar:
    logo: fig/usyd-logo.png
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: setup.html
        text: "Setup"
      - text: "Session 1"
        menu:
        - text: "Python from ipynb example"
          href: notebooks/01a-fundamentals.html
        - text: "R from qmd example"
          href: notebooks/01b_exampleRcontent.html
        - text: "Markdown from md example"
          href: notebooks/01c_exampleMDcontent.html
  page-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"

format:
  html:
    include-in-header: 
      - text: |
          <script data-goatcounter="https://sih.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
    link-external-newwindow: true
    link-external-icon: true
    toc: true
    css: [lesson.css]
    theme: cosmo
    code-link: true
    code-fold: false
   
